name: Ping Render API

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Predict API
        run: |
          curl -X POST https://your-api.onrender.com/predict \
          -H "Content-Type: application/json" \
          -d '{"lead_time":5,"stock":100,"feature1":10,"feature2":20}'
